### ISSUE TITLE
Incorrect path for static file `images/rit.png`

### ISSUE THREAD

**Issue by robellegate** [FOSSRIT/knowledgebase#2]
As per the [Hugo content management documentation](https://gohugo.io/content-management/static-files/), static files are served from the site root path. The RIT logo in [static/images/rit.png](https://github.com/FOSSRIT/knowledgebase/blob/master/static/images/rit.png) as referenced below is incorrect.

https://github.com/FOSSRIT/knowledgebase/blob/2f5ed7a646326b20b5fbdeef718ab5a8abca5e85/config.toml#L57

Instead, it should be referenced as:
```toml
############################# Default parameters ##########################
[params]
logo = "images/rit.png"
```
